### ISSUE TITLE
Where's nerfstudio VisibilityFIeld come from?

### ISSUE THREAD

**Issue by jaggzh** [ethanweber/nerfbusters#17]
```
$ ns-train nerfbusters --help
Traceback (most recent call last):
...
"...python3.11/site-packages/nerfbusters/nerf/nerfbusters_pipeline.py", line 42, in <module>
from nerfstudio.fields.visibility_field import VisibilityField
ModuleNotFoundError: No module named 'nerfstudio.fields.visibility_field'
```

I don't see that in their source or my web searches.

**Comment by jaggzh** [comment]
Found your PR. Trying it out now.
https://github.com/nerfstudio-project/nerfstudio/pull/2264

**Comment by jaggzh** [comment]
Making progress. Got some incompatibility though:
```
Traceback (most recent call last):
File "/home/j/venvs/gaussian-dream/bin/ns-train", line 8, in <module>
sys.exit(entrypoint())
^^^^^^^^^^^^
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
main(
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
launch(
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
trainer.setup()
File "/home/j/src/nerf/nerfstudio/nerfstudio/engine/trainer.py", line 147, in setup
self.pipeline = self.config.pipeline.setup(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/j/src/nerf/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
return self._target(self, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NerfbustersPipeline.__init__() got an unexpected keyword argument 'grad_scaler'
```

**Comment by ethanweber** [comment]
Hey @jaggzh, so it should work if you use this branch https://github.com/nerfstudio-project/nerfstudio/tree/nerfbusters-changes, but if you want to use the latest Nerfstudio version (which I recommend), you could just take the necessary changes from that PR. I think the code could be written in a way where you can use the latest version of Nerfstudio. This would mean moving the visibility field and other relevant code into your project (or, into the nerfbusters codebase) rather than having changes in both places. That would be the ideal setup since we decided ultimately to not merge that PR into the main branch, since it's kind of specific to Nerfbusters. It would have been better to do all the changes in the Nerfbusters repo.

Also, make sure you rerun `pip install -e .` whenever changing the Nerfstudio branch. Good luck! :)

**Comment by jaggzh** [comment]
Been working hard on this stuff, I swear it! :)
I'm using the nerfbusters branch of nerfstudio now.
First issue was in `nerfbusters/nerf/nerfbusters_config.py`.
(no depth_method keyword exists to NerfbustersPipelineConfig:
`model=NerfactoModelConfig(eval_num_rays_per_chunk=1 << 15, predict_normals=True), #, depth_method="median"),`
I commented it out for now).

Now I'm not sure what to do about the grad_scaler: 
```
File "/home/j/venvs/gaussian-dream/bin/ns-train", line 8, in <module>
sys.exit(entrypoint())
^^^^^^^^^^^^
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
main(
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
launch(
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "/home/j/src/nerf/nerfstudio/nerfstudio/scripts/train.py", line 99, in train_loop
trainer.setup()
File "/home/j/src/nerf/nerfstudio/nerfstudio/engine/trainer.py", line 147, in setup
self.pipeline = self.config.pipeline.setup(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/j/src/nerf/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
return self._target(self, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NerfbustersPipeline.__init__() got an unexpected keyword argument 'grad_scaler'
```

**Comment by ethanweber** [comment]
Thanks for working through it! Maybe this line is helpful for the depth method part. https://github.com/nerfstudio-project/nerfstudio/blob/b03e9beccdee2807bea71783f42b71fad5f2992e/nerfstudio/models/nerfacto.py#L130. It seems like it's maybe not using the branch you want.
