### ISSUE TITLE
len(optimizer_state["found_inf_per_device"]) > 0 -- AssertionError: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by jaggzh** [ethanweber/nerfbusters#19]
Okay not sure if this is from nerfbusters or ns (but I feel I'm getting closer to this working! (famous last words?))

```python
Viewer at: https://viewer.nerf.studio/versions/23-03-9-0/?websocket_url=ws://localhost:7007
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.4158              
NerfbustersPipeline.get_train_loss_dict: 0.3650              
Traceback (most recent call last):
  File "/home/j/venvs/ns/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/j/venvs/ns/lib/python3.11/site-packages/scripts/train.py", line 247, in entrypoint
    main(
  File "/home/j/venvs/ns/lib/python3.11/site-packages/scripts/train.py", line 233, in main
    launch(
  File "/home/j/venvs/ns/lib/python3.11/site-packages/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/j/venvs/ns/lib/python3.11/site-packages/scripts/train.py", line 87, in train_loop
    trainer.train()
  File "/home/j/src/nerf/nerfstudio/nerfstudio/engine/trainer.py", line 225, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/src/nerf/nerfstudio/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/src/nerf/nerfstudio/nerfstudio/engine/trainer.py", line 421, in train_iteration
    self.optimizers.optimizer_scaler_step_all(self.grad_scaler)
  File "/home/j/src/nerf/nerfstudio/nerfstudio/engine/optimizers.py", line 130, in optimizer_scaler_step_all
    grad_scaler.step(optimizer)
  File "/home/j/venvs/ns/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py", line 413, in step
    len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
```

**Comment by ethanweber** [comment]
How long did this train for? I've seen this error before but can't quite recall where. I think it's a Nerfstudio thing when the model diverges.
