### ISSUE TITLE
ImportError: cannot import name 'eval_setup' from partially initialized module 'nerfstudio.utils.eval_utils'

### ISSUE THREAD

**Issue by FCInter** [ethanweber/nerfbusters#21]
Here is the error. I can run the exporter of nerfstudio successfully. But after I installed nerfbusters, `from nerfstudio.utils.eval_utils import eval_setup` this command reports me an error.

Previously I met with almost all the errors reported in previous issues, such as `visibility_fields`, `depth_method`, etc. 

```
>>> from nerfstudio.utils.eval_utils import eval_setup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mypath/projects/nerfstudio/nerfstudio/utils/eval_utils.py", line 28, in <module>
    from nerfstudio.configs.method_configs import all_methods
  File "/home/mypath/projects/nerfstudio/nerfstudio/configs/method_configs.py", line 669, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/home/mypath/projects/nerfstudio/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/home/mypath/.conda/envs/nerfstudio/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "/home/mypath/.conda/envs/nerfstudio/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mypath/projects/nerfbusters/nerfbusters/nerf/nerfbusters_config.py", line 16, in <module>
    from nerfbusters.nerf.nerfbusters_pipeline import NerfbustersPipelineConfig
  File "/home/mypath/projects/nerfbusters/nerfbusters/nerf/nerfbusters_pipeline.py", line 29, in <module>
    from nerfbusters.cubes.visualize3D import get_image_grid
  File "/home/mypath/projects/nerfbusters/nerfbusters/cubes/visualize3D.py", line 13, in <module>
    from nerfbusters.cubes.datasets3D import Crop
  File "/home/mypath/projects/nerfbusters/nerfbusters/cubes/datasets3D.py", line 29, in <module>
    from nerfstudio.utils.eval_utils import eval_setup
ImportError: cannot import name 'eval_setup' from partially initialized module 'nerfstudio.utils.eval_utils' (most likely due to a circular import) (/home/mypath/projects/nerfstudio/nerfstudio/utils/eval_utils.py)
```

**Comment by ethanweber** [comment]
Hi, I'm not sure what's going on. My best bet is you aren't on the branch that we support: https://github.com/nerfstudio-project/nerfstudio/tree/nerfbusters-changes.
