### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'grad_scaler'

### ISSUE THREAD

**Issue by FCInter** [ethanweber/nerfbusters#22]
I also meet this problem. I find another person post this issue but is not replied. I'm looking forward to a solution. Thank you!

```
Traceback (most recent call last):
  File "/home/mypath/.conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/mypath/projects/nerfstudio/nerfstudio/scripts/train.py", line 275, in entrypoint
    main(
  File "/home/mypath/projects/nerfstudio/nerfstudio/scripts/train.py", line 258, in main
    launch(
  File "/home/mypath/projects/nerfstudio/nerfstudio/scripts/train.py", line 193, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/mypath/projects/nerfstudio/nerfstudio/scripts/train.py", line 102, in train_loop
    trainer.setup()
  File "/home/mypath/projects/nerfstudio/nerfstudio/engine/trainer.py", line 149, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/mypath/projects/nerfstudio/nerfstudio/configs/base_config.py", line 59, in setup
    return self._target(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'grad_scaler'
```

**Comment by ethanweber** [comment]
Hi, so our code is on a branch mentioned in the README. It's using an older version of Nerfstudio, which probably contributes to this error. You might wish to reference this branch and incorporate parts you want into your own codebase, given that Nerfstudio keeps improving. https://github.com/nerfstudio-project/nerfstudio/tree/nerfbusters-changes
